import { FeedItem } from './types';

export const mockFeedItems: FeedItem[] = [
  // ==================== 2026-05-09 (今天) ====================
  {
    id: '1',
    title: '字节跳动2027届提前批校招正式启动，技术岗位HC超5000',
    summary: '字节跳动宣布2027届校园招聘提前批正式启动，涵盖研发、产品、设计等岗位。技术类岗位HC超过5000个，算法、后端、前端需求最大。提前批投递截止时间为6月30日，建议同学们尽早准备。',
    url: 'https://jobs.bytedance.com/campus',
    source: '字节跳动招聘',
    channel: 'official',
    category: 'internship',
    tags: ['字节跳动', '校招', '提前批', '技术岗'],
    score: 95,
    featured: true,
    createdAt: '2026-05-09T10:00:00+08:00',
  },
  {
    id: '2',
    title: '腾讯2027届产品经理培训生项目开放申请',
    summary: '腾讯产品经理培训生项目正式启动，面向2027届毕业生。该项目以"产品经理黄埔军校"著称，培养体系完善，往年录取率约1%。需要通过在线测评、群面、单面等多轮考核。',
    url: 'https://join.qq.com/product',
    source: '腾讯招聘',
    channel: 'official',
    category: 'internship',
    tags: ['腾讯', '产品经理', '培训生', '校招'],
    score: 92,
    featured: true,
    createdAt: '2026-05-09T09:30:00+08:00',
  },
  {
    id: '3',
    title: '美团技术团队面试经验分享：后端开发岗三轮面试全记录',
    summary: '一位拿到美团后端开发offer的同学分享了完整的面试经历。一面主要考察基础知识和算法，二面深入项目经验，三面是技术leader的综合面试。文章详细记录了每轮面试的具体问题和回答思路。',
    url: 'https://zhuanlan.zhihu.com/p/meituan-interview',
    source: '知乎',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/1234567',
    sourceHandle: '@程序员小王',
    channel: 'social',
    category: 'interview',
    tags: ['美团', '面试经验', '后端', '校招'],
    score: 88,
    createdAt: '2026-05-09T14:20:00+08:00',
  },
  {
    id: '4',
    title: '2026年互联网行业薪资报告出炉：应届生平均月薪18K',
    summary: '某招聘平台发布2026年互联网行业薪资报告。数据显示，应届生平均月薪达到18K，其中算法工程师以25K领跑，前端和后端开发分别为17K和19K。大厂校招薪资普遍高于行业平均30%以上。',
    url: 'https://www.lagou.com/salary-report-2026',
    source: '拉勾网',
    channel: 'news',
    category: 'salary',
    tags: ['薪资报告', '互联网', '应届生', '行业分析'],
    score: 85,
    createdAt: '2026-05-09T11:00:00+08:00',
  },
  {
    id: '5',
    title: '简历这样写，HR 3秒内就会注意到你',
    summary: '资深HR分享简历筛选逻辑：平均每份简历只看3-6秒。文章总结了5个让简历脱颖而出的技巧：量化成果、突出关键词、控制在一页、排版简洁、针对性修改。附带10份优秀简历模板下载。',
    url: 'https://mp.weixin.qq.com/resume-tips',
    source: '求职辅导',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/2345678',
    sourceHandle: '@HR老张',
    channel: 'social',
    category: 'resume',
    tags: ['简历', '求职技巧', 'HR', '模板'],
    score: 82,
    createdAt: '2026-05-09T16:45:00+08:00',
  },
  {
    id: '6',
    title: '阿里云2027届实习生招聘开启，转正率高达70%',
    summary: '阿里云启动2027届暑期实习生招聘，技术岗位覆盖云计算、数据库、中间件等方向。往年实习生转正率高达70%，是进入阿里的重要通道。实习期间提供免费住宿和餐补。',
    url: 'https://talent.alibaba.com/intern',
    source: '阿里巴巴招聘',
    channel: 'official',
    category: 'internship',
    tags: ['阿里云', '实习', '转正', '云计算'],
    score: 90,
    createdAt: '2026-05-09T08:00:00+08:00',
  },
  {
    id: '7',
    title: 'AI面试助手工具测评：这5款最值得用',
    summary: '随着AI技术发展，越来越多求职者使用AI工具辅助面试准备。本文测评了市面上5款主流AI面试助手，从模拟面试、简历优化、薪资谈判等维度进行对比。其中ChatGPT和Claude在模拟面试场景表现最佳。',
    url: 'https://www.36kr.com/p/ai-interview-tools',
    source: '36氪',
    channel: 'news',
    category: 'tips',
    tags: ['AI工具', '面试准备', '求职', '测评'],
    score: 78,
    createdAt: '2026-05-09T13:30:00+08:00',
  },
  {
    id: '8',
    title: '快手算法岗面试真题汇总（2026最新版）',
    summary: '整理了快手算法岗近半年的面试真题，涵盖机器学习基础、深度学习、推荐系统、NLP等方向。每道题目都附带详细解答思路和参考答案。建议先自己思考再看答案，效果更好。',
    url: 'https://www.nowcoder.com/kuaishou-algorithm',
    source: '牛客网',
    channel: 'news',
    category: 'interview',
    tags: ['快手', '算法', '面试真题', '校招'],
    score: 86,
    createdAt: '2026-05-09T15:00:00+08:00',
  },
  {
    id: '9',
    title: '小红书产品经理面试复盘：从群面到终面全流程',
    summary: '详细记录了小红书产品经理校招的完整面试流程。群面是无领导小组讨论，二面是业务面试，三面是交叉面，最后是HR面。作者分享了每个环节的注意事项和自己的表现反思。',
    url: 'https://www.xiaohongshu.com/pm-interview',
    source: '小红书',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/3456789',
    sourceHandle: '@产品小姐姐',
    channel: 'social',
    category: 'interview',
    tags: ['小红书', '产品经理', '面试复盘', '群面'],
    score: 80,
    createdAt: '2026-05-09T17:30:00+08:00',
  },

  // ==================== 2026-05-08 (昨天) ====================
  {
    id: '10',
    title: '华为2027届天才少年计划启动，最高年薪201万',
    summary: '华为正式启动2027届"天才少年"招聘计划，面向全球顶尖高校博士毕业生。入选者最高可获得201万年薪，目前已有20余位天才少年加入华为。要求在数学、计算机、物理等领域有突出成果。',
    url: 'https://career.huawei.com/genius',
    source: '华为招聘',
    channel: 'official',
    category: 'internship',
    tags: ['华为', '天才少年', '博士', '高薪'],
    score: 94,
    featured: true,
    createdAt: '2026-05-08T10:30:00+08:00',
  },
  {
    id: '11',
    title: '大厂校招笔试攻略：行测+专业题+编程题全面解析',
    summary: '系统梳理了互联网大厂校招笔试的三大题型：行测题（逻辑推理、数量关系）、专业题（计算机基础、网络、操作系统）、编程题（算法与数据结构）。提供了每个题型的备考策略和刷题资源推荐。',
    url: 'https://www.zhihu.com/p/written-test-guide',
    source: '知乎',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/4567890',
    sourceHandle: '@刷题达人',
    channel: 'social',
    category: 'tips',
    tags: ['笔试', '校招', '行测', '编程'],
    score: 83,
    createdAt: '2026-05-08T14:00:00+08:00',
  },
  {
    id: '12',
    title: '京东2027届管培生项目开放申请',
    summary: '京东管理培训生项目启动，面向2027届优秀毕业生。项目提供轮岗机会，涵盖电商、物流、金融等业务线。往年管培生晋升速度快，3年内可晋升至中层管理岗位。',
    url: 'https://jd.zhaopin.com/mt',
    source: '京东招聘',
    channel: 'official',
    category: 'internship',
    tags: ['京东', '管培生', '校招', '管理'],
    score: 87,
    createdAt: '2026-05-08T09:00:00+08:00',
  },
  {
    id: '13',
    title: '2026届秋招复盘：我拿了10个大厂offer',
    summary: '一位计算机专业同学分享了自己秋招斩获10个大厂offer的经历。从准备策略、投递节奏、面试技巧到最终选择，详细记录了整个求职过程。重点强调了项目经验和算法能力的重要性。',
    url: 'https://www.nowcoder.com/offer-experience',
    source: '牛客网',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/5678901',
    sourceHandle: '@offer收割机',
    channel: 'social',
    category: 'interview',
    tags: ['秋招', 'offer', '经验分享', '大厂'],
    score: 89,
    createdAt: '2026-05-08T16:20:00+08:00',
  },
  {
    id: '14',
    title: '简历中的项目经历怎么写？STAR法则详解',
    summary: '深入讲解如何用STAR法则（情境、任务、行动、结果）描述项目经历。通过对比修改前后的简历片段，展示如何让项目描述更有说服力。附赠10个项目经历写作模板。',
    url: 'https://www.jianshu.com/p/star-method',
    source: '简书',
    channel: 'news',
    category: 'resume',
    tags: ['简历', '项目经历', 'STAR法则', '写作技巧'],
    score: 76,
    createdAt: '2026-05-08T11:30:00+08:00',
  },
  {
    id: '15',
    title: '新能源汽车行业校招薪资盘点：蔚来、理想、小鹏对比',
    summary: '对比分析了蔚来、理想、小鹏三家新能源车企的校招薪资水平。研发岗位年薪普遍在25-40万之间，高于传统车企。文章还分析了各公司的业务前景和职业发展路径。',
    url: 'https://www.autohome.com/salary-compare',
    source: '汽车之家',
    channel: 'news',
    category: 'salary',
    tags: ['新能源汽车', '薪资', '蔚来', '理想', '小鹏'],
    score: 81,
    createdAt: '2026-05-08T13:45:00+08:00',
  },
  {
    id: '16',
    title: '网易游戏2027届校招启动，游戏策划岗位最热门',
    summary: '网易游戏启动2027届校园招聘，涵盖游戏研发、游戏策划、游戏美术等岗位。其中游戏策划岗位竞争最激烈，报录比超过100:1。建议投递者提前准备游戏分析作品集。',
    url: 'https://game.163.com/campus',
    source: '网易游戏招聘',
    channel: 'official',
    category: 'internship',
    tags: ['网易游戏', '校招', '游戏策划', '游戏研发'],
    score: 88,
    createdAt: '2026-05-08T10:00:00+08:00',
  },
  {
    id: '17',
    title: '面试被问到"你的缺点是什么"该怎么回答？',
    summary: '这是面试中最常见也最容易答错的问题之一。文章分析了HR问这个问题的真实目的，提供了3种高分回答模板，并列举了5个绝对不能说的"假缺点"。建议结合具体案例说明改进措施。',
    url: 'https://www.zhihu.com/question/weakness',
    source: '知乎',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/6789012',
    sourceHandle: '@面试教练',
    channel: 'social',
    category: 'interview',
    tags: ['面试', '缺点', 'HR', '回答技巧'],
    score: 74,
    createdAt: '2026-05-08T15:30:00+08:00',
  },

  // ==================== 2026-05-07 (前天) ====================
  {
    id: '18',
    title: '拼多多2027届校招提前批启动，技术岗薪资对标字节',
    summary: '拼多多宣布2027届校招提前批正式启动，技术岗位薪资对标字节跳动，应届生总包可达50万+。公司实行大小周，但加班费和年终奖丰厚。工作地点主要在上海和广州。',
    url: 'https://pinduoduo.zhaopin.com/campus',
    source: '拼多多招聘',
    channel: 'official',
    category: 'internship',
    tags: ['拼多多', '校招', '技术岗', '高薪'],
    score: 91,
    featured: true,
    createdAt: '2026-05-07T09:00:00+08:00',
  },
  {
    id: '19',
    title: '银行科技岗校招指南：国有行vs股份行vs互联网银行',
    summary: '全面对比了国有大行、股份制银行和互联网银行的科技岗校招差异。国有行稳定但薪资较低，股份行薪资适中发展空间大，互联网银行薪资高但压力大。附各银行笔试面试时间线。',
    url: 'https://www.yicai.com/bank-tech',
    source: '第一财经',
    channel: 'news',
    category: 'industry',
    tags: ['银行', '科技岗', '校招', '行业对比'],
    score: 79,
    createdAt: '2026-05-07T11:00:00+08:00',
  },
  {
    id: '20',
    title: '无实习经历如何拿到大厂offer？这份攻略帮你逆袭',
    summary: '很多同学担心没有实习经历会影响求职。本文分享了5个弥补方案：开源项目贡献、参加技术竞赛、做有深度的课程设计、考取专业证书、参加线上训练营。关键是让面试官看到你的学习能力。',
    url: 'https://www.nowcoder.com/no-internship-guide',
    source: '牛客网',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/7890123',
    sourceHandle: '@逆袭学长',
    channel: 'social',
    category: 'tips',
    tags: ['实习', '大厂', '求职技巧', '逆袭'],
    score: 84,
    createdAt: '2026-05-07T14:30:00+08:00',
  },
  {
    id: '21',
    title: '抖音前端团队面试题汇总（含答案解析）',
    summary: '整理了抖音前端团队近期的面试真题，涵盖JavaScript基础、React原理、性能优化、工程化等方向。每道题目都配有详细的答案解析和知识点延伸，适合准备前端面试的同学。',
    url: 'https://github.com/douyin-fe-interview',
    source: 'GitHub',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/8901234',
    sourceHandle: '@前端小张',
    channel: 'social',
    category: 'interview',
    tags: ['抖音', '前端', '面试题', 'JavaScript'],
    score: 82,
    createdAt: '2026-05-07T16:00:00+08:00',
  },
  {
    id: '22',
    title: '2026年AI行业人才需求报告：算法工程师缺口最大',
    summary: '最新行业报告显示，AI相关岗位需求同比增长40%，其中算法工程师缺口最大。大模型、AIGC、自动驾驶方向人才最紧缺。报告还分析了各城市AI岗位分布和薪资水平。',
    url: 'https://www.51job.com/ai-report-2026',
    source: '前程无忧',
    channel: 'news',
    category: 'industry',
    tags: ['AI', '人才需求', '算法工程师', '行业报告'],
    score: 86,
    createdAt: '2026-05-07T10:30:00+08:00',
  },
  {
    id: '23',
    title: '小米2027届校招启动，汽车业务成新亮点',
    summary: '小米集团启动2027届校园招聘，涵盖手机、AIoT、汽车三大业务线。其中汽车业务是今年招聘亮点，自动驾驶、智能座舱等岗位需求旺盛。小米汽车工厂位于北京亦庄。',
    url: 'https://hr.xiaomi.com/campus',
    source: '小米招聘',
    channel: 'official',
    category: 'internship',
    tags: ['小米', '校招', '汽车', '自动驾驶'],
    score: 87,
    createdAt: '2026-05-07T08:30:00+08:00',
  },
  {
    id: '24',
    title: '简历投递后石沉大海？可能是这5个原因',
    summary: '很多同学反映投递简历后没有回音。本文分析了5个常见原因：简历与岗位不匹配、投递时间不对、简历格式问题、学历/专业硬性要求、内推渠道更有效。针对每个原因给出了改进建议。',
    url: 'https://www.zhihu.com/p/resume-no-reply',
    source: '知乎',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/9012345',
    sourceHandle: '@求职顾问',
    channel: 'social',
    category: 'resume',
    tags: ['简历', '投递', '求职', '内推'],
    score: 75,
    createdAt: '2026-05-07T13:00:00+08:00',
  },
  {
    id: '25',
    title: 'B站2027届校招启动，二次元浓度最高的互联网公司',
    summary: '哔哩哔哩启动2027届校园招聘，涵盖技术、产品、运营、内容等岗位。作为二次元浓度最高的互联网公司，B站工作氛围年轻化，弹性工作制，还有免费健身房和游戏室。',
    url: 'https://jobs.bilibili.com/campus',
    source: '哔哩哔哩招聘',
    channel: 'official',
    category: 'internship',
    tags: ['B站', '校招', '二次元', '互联网'],
    score: 83,
    createdAt: '2026-05-07T11:30:00+08:00',
  },
  {
    id: '26',
    title: '技术面试中的系统设计题怎么答？',
    summary: '系统设计是中高级技术面试的必考题型。本文讲解了系统设计面试的标准答题框架：需求澄清、容量估算、系统架构设计、数据存储方案、扩展性讨论。以"设计一个短链接系统"为例详细演示。',
    url: 'https://www.jianshu.com/p/system-design',
    source: '简书',
    sourceAvatar: 'https://avatars.githubusercontent.com/u/12345678',
    sourceHandle: '@架构师老李',
    channel: 'social',
    category: 'interview',
    tags: ['系统设计', '技术面试', '架构', '后端'],
    score: 80,
    createdAt: '2026-05-07T15:45:00+08:00',
  },
  {
    id: '27',
    title: '外企校招指南：微软、谷歌、亚马逊中国校招全解析',
    summary: '详细介绍了微软、谷歌、亚马逊三家外企的中国校招流程。外企面试更注重算法和系统设计，工作生活平衡好，但HC相对较少。文章还对比了外企与国内大厂的薪资福利差异。',
    url: 'https://www.infoq.cn/article/foreign-company-campus',
    source: 'InfoQ',
    channel: 'news',
    category: 'industry',
    tags: ['外企', '微软', '谷歌', '亚马逊', '校招'],
    score: 85,
    createdAt: '2026-05-07T09:30:00+08:00',
  },
  {
    id: '28',
    title: '数据分析岗校招面试必备：SQL和Python考点汇总',
    summary: '整理了数据分析岗位校招面试中SQL和Python的高频考点。SQL部分重点考察多表连接、窗口函数、子查询；Python部分重点考察pandas数据处理、数据可视化、基础统计知识。',
    url: 'https://www.kesci.com/data-analysis-interview',
    source: '和鲸社区',
    channel: 'news',
    category: 'interview',
    tags: ['数据分析', 'SQL', 'Python', '面试'],
    score: 77,
    createdAt: '2026-05-07T17:00:00+08:00',
  },
];
