import { FeedItem } from './types';
import campusData from './campus-data.json';

// Import real data from Campus2026 parsed JSON
// The data is generated by: npx tsx scripts/parse-campus2026.ts
export const feedItems: FeedItem[] = campusData as FeedItem[];
