// 求职导航数据：按分类组织的常用求职网站集合
// 数据来源：从 jobpilot 飞书导航表清洗导出，覆盖官方平台、央企、银行、文化企业、选调事业单位等

export interface NavSite {
  name: string;
  url: string;
  desc?: string;
}

export interface NavCategory {
  category: string;
  sites: NavSite[];
}

export const NAV_DATA: NavCategory[] = [
  {
    category: '官方招聘平台',
    sites: [
      { name: '中华人民共和国人力资源和社会保障部', url: 'http://www.mohrss.gov.cn/SYrlzyhshbzb/fwyd/SYkaoshizhaopin/zyhgjjgsydwgkzp/' },
      { name: '国务院国有资产监督管理委员会', url: 'http://www.sasac.gov.cn/n2588035/n2588325/n2588350/index.html' },
      { name: '教育部人才服务网', url: 'https://jybzp.chsi.com.cn/home/index' },
      { name: '国家人力资源和社会保障部', url: 'http://www.mohrss.gov.cn/' },
      { name: '事业单位招聘考试网', url: 'http://www.shiyebian.net/' },
      { name: '中央企业2024年招聘（国务院官方发布）', url: 'http://www.sasac.gov.cn/n4470048/n26915116/n28754408/index.html' },
      { name: '国家高校毕业生就业服务平台', url: 'http://job.mohrss.gov.cn/202008gx/index.jhtml' },
      { name: '中国公共招聘网', url: 'http://job.mohrss.gov.cn/' },
      { name: '国家技能人才评价服务', url: 'http://osta.mohrss.gov.cn/' },
      { name: '24365国家大学生就业平台', url: 'https://www.ncss.cn/student/24365' },
      { name: '国聘网（国企大全）', url: 'https://xiaoyuan.iguopin.com/' },
      { name: '应届生求职网', url: 'https://www.yingjiesheng.com/' },
      { name: '前程无忧', url: 'https://www.51job.com/' },
      { name: '智联招聘', url: 'https://www.zhaopin.com/' },
      { name: 'BOSS直聘', url: 'https://www.zhipin.com/' },
      { name: '猎聘', url: 'https://www.liepin.com/' },
      { name: '牛客网', url: 'https://www.nowcoder.com/' },
      { name: '刺猬实习', url: 'https://www.ciwei.net/' },
      { name: '实习僧', url: 'https://www.shixiseng.com/' },
      { name: '国家公务员局', url: 'http://bm.scs.gov.cn/pp/gkweb/core/web/ui/business/home/gkhome.html' },
      { name: '军队人才网', url: 'http://81rc.81.cn/wzry/' },
      { name: '中国烟草人才招聘平台', url: 'http://www.tobacco.gov.cn/gjyc/zpxx/list.shtml' },
      { name: '南方电网', url: 'https://zhaopin.csg.cn/#/index' },
      { name: '中国铁路人才招聘网', url: 'https://rczp.china-railway.com.cn/page/recruitment/rec_info.html' },
    ],
  },
  {
    category: '央企招聘',
    sites: [
      { name: '中国核工业集团有限公司', url: 'https://cnnc.zhiye.com/' },
      { name: '中国航天科技集团有限公司', url: 'https://www.spacetalent.com.cn/' },
      { name: '中国航天科工集团有限公司', url: 'http://www.casic.com.cn/n27219851/n27219940/index.html' },
      { name: '中国航空工业集团有限公司', url: 'https://www.avic.com.cn/hdjl/jtgg/' },
      { name: '中国船舶集团有限公司', url: 'http://www.csic.com.cn/n9/n63/index.html' },
      { name: '中国兵器工业集团有限公司', url: 'http://www.norincogroup.com.cn/col/col187/index.html' },
      { name: '中国兵器装备集团有限公司', url: 'https://www.csgc.com.cn/csgc/rlzy/rczp/A003006005Gone1.html' },
      { name: '中国电子科技集团有限公司', url: 'http://www.cetc.com.cn/zgdk/1593022/1592495/index.html' },
      { name: '中国航空发动机集团有限公司', url: 'https://aecc.iguopin.com/' },
      { name: '中国融通资产管理集团有限公司', url: 'https://www.crtamg.com.cn/rlzy/rczp/' },
      { name: '中国石油天然气集团有限公司', url: 'https://www.cnpc.com.cn/cnpc/jrwm/jrwm_index.shtml' },
      { name: '中国石油化工集团有限公司', url: 'http://job.sinopec.com/#/index' },
      { name: '中国海洋石油集团有限公司', url: 'https://www.cnooc.com.cn/col/col1381/index.html' },
      { name: '国家石油天然气管网集团有限公司', url: 'https://wecruit.hotjob.cn/SU617b87702f9d247cb97cc6b7/pb/index.html#/' },
      { name: '国家电网有限公司', url: 'https://zhaopin.sgcc.com.cn/sgcchr/static/home.html' },
      { name: '中国南方电网有限责任公司', url: 'https://zhaopin.csg.cn/#/' },
      { name: '中国华能集团有限公司', url: 'https://www.chng.com.cn/list_zpxx/-/article/cQQKaBtwslFy/list/23524.html' },
      { name: '中国大唐集团有限公司', url: 'https://zhaopin.china-cdt.com/zpgg_index.html' },
      { name: '中国华电集团有限公司', url: 'https://www.chd.com.cn/site/2/list/c802da7172754e8f8a3fc3bc02d7bfd7_1.html' },
      { name: '国家电力投资集团有限公司', url: 'http://www.spic.com.cn/2021/jrwm/' },
      { name: '中国长江三峡集团有限公司', url: 'https://chrcmp.chinahr.com/pages/sanxia/' },
      { name: '国家能源投资集团有限责任公司', url: 'https://zhaopin.chnenergy.com.cn/' },
      { name: '中国电信集团有限公司', url: 'http://www.chinatelecom.com.cn/zp/' },
      { name: '中国联合网络通信集团有限公司', url: 'http://www.chinaunicom.com.cn/46/menu01/528/column06' },
      { name: '中国移动通信集团有限公司', url: 'https://job.10086.cn/' },
      { name: '中国卫星网络集团有限公司', url: 'https://job.iguopin.com/company?id=c9675c1112d741480481894415200256' },
      { name: '中国电子信息产业集团有限公司', url: 'https://cec.hotjob.cn/' },
      { name: '中国第一汽车集团有限公司', url: 'https://faw-zhaopin.hotjob.cn/' },
      { name: '东风汽车集团有限公司', url: 'https://dfmc.hotjob.cn/' },
      { name: '中国一重集团有限公司', url: 'http://www.cfhi.com/yizhonggroup/rlzy/rczp/index.shtml' },
      { name: '中国机械工业集团有限公司', url: 'https://zhaopin.sinomach.com.cn/' },
      { name: '哈尔滨电气集团有限公司', url: 'https://www.harbin-electric.com/human3.asp' },
      { name: '中国东方电气集团有限公司', url: 'https://www.dongfang.com/zxns/gdrc.htm' },
      { name: '鞍钢集团有限公司', url: 'http://www.ansteel.cn/kechixufazhan/renliziyuan/zhaopinxinxi/' },
      { name: '中国宝武钢铁集团有限公司', url: 'https://campus.51job.com/baowugroup2024/' },
      { name: '中国矿产资源集团有限公司(23年后无校招)', url: 'https://campus.51job.com/p/cmr/campus' },
      { name: '中国铝业集团有限公司', url: 'https://www.chinalco.com.cn/rlzy/rlzy_zpxx/' },
      { name: '中国远洋海运集团有限公司', url: 'https://www.coscoshipping.com/col9555/art/2022/art_9555_287771.html' },
      { name: '中国航空集团有限公司', url: 'http://zhaopin.airchina.com.cn/' },
      { name: '中国东方航空集团有限公司', url: 'https://job.ceair.com/' },
      { name: '中国南方航空集团有限公司', url: 'https://job.csair.cn/#/home' },
      { name: '中国中化控股有限责任公司', url: 'https://sinochem.hotjob.cn/' },
      { name: '中粮集团有限公司', url: 'https://cofco-campus.zhaopin.com/' },
      { name: '中国五矿集团有限公司', url: 'https://wecruit.hotjob.cn/SU62f37858bef57c29ead8adab/pb/index.html#/' },
      { name: '中国通用技术（集团）控股有限责任公司', url: 'https://www.gt.cn/rlzy/zpxx/' },
      { name: '中国建筑集团有限公司', url: 'https://recruit.cscec.com/recruit#/index_nav?contract_unit=31997577&company_id=1873' },
      { name: '中国储备粮管理集团有限公司', url: 'https://www.sinograin.com.cn/join.html?navId=7&navPid=0' },
      { name: '中国南水北调集团有限公司', url: 'http://www.csnwd.com.cn/xxgk/cpyc/' },
      { name: '国家开发投资集团有限公司', url: 'https://sdic.iguopin.com/' },
    ],
  },
  {
    category: '中央金融企业',
    sites: [
      { name: '中国国家铁路集团有限公司', url: 'http://www.china-railway.com.cn/' },
      { name: '中国烟草总公司', url: 'http://www.tobacco.gov.cn/html/' },
      { name: '中国邮政集团有限公司', url: 'http://www.chinapost.com.cn/' },
      { name: '北大荒农垦集团有限公司', url: 'http://www.chinabdh.com/' },
      { name: '中国投资有限责任公司', url: 'http://www.china-inv.cn/' },
      { name: '国家开发银行', url: 'http://www.cdb.com.cn/' },
      { name: '中国进出口银行', url: 'http://www.eximbank.gov.cn/' },
      { name: '中国农业发展银行', url: 'http://www.adbc.com.cn/' },
      { name: '中国工商银行股份有限公司', url: 'http://www.icbc-ltd.com/icbcltd/' },
      { name: '中国农业银行股份有限公司', url: 'http://www.abchina.com/cn/' },
      { name: '中国银行股份有限公司', url: 'https://www.boc.cn/' },
      { name: '中国建设银行股份有限公司', url: 'http://www.ccb.com/cn/home/indexv3.html' },
      { name: '交通银行股份有限公司', url: 'http://www.bankcomm.com/BankCommSite/default.shtml' },
      { name: '中国中信集团有限公司', url: 'https://www.group.citic/' },
      { name: '中国光大集团股份公司', url: 'https://www.ebchina.com/' },
      { name: '中国人民保险集团股份有限公司', url: 'https://www.picc.com/' },
      { name: '中国人寿保险（集团）公司', url: 'https://www.e-chinalife.com/' },
      { name: '中国太平保险集团有限责任公司', url: 'http://www.cntaiping.com/' },
      { name: '中国出口信用保险公司', url: 'http://www.sinosure.com.cn/' },
      { name: '中国华融资产管理股份有限公司', url: 'http://www.chamc.com.cn/' },
      { name: '中国长城资产管理股份有限公司', url: 'http://www.gwamcc.com/' },
      { name: '中国东方资产管理股份有限公司', url: 'http://www.coamc.com.cn/' },
      { name: '中国信达资产管理股份有限公司', url: 'http://www.cinda.com.cn/xdjt/xdjtpd/index.shtml' },
      { name: '中央国债登记结算有限责任公司', url: 'http://www.ccdc.com.cn/ccdc/cn/index/index.shtml' },
      { name: '中国农业再保险股份有限公司', url: 'http://www.china-agrore.com/' },
      { name: '中国政企合作投资基金股份有限公司', url: 'http://www.cpppf.org/index.html' },
      { name: '国家融资担保基金有限责任公司', url: 'https://www.gjrdjj.com/' },
      { name: '国家农业信贷担保联盟有限责任公司', url: 'http://guojianongdan.cn/' },
      { name: '中国再保险（集团）股份有限公司', url: 'https://www.chinare.com.cn/' },
      { name: '中国建银投资有限责任公司', url: 'http://www.jic.cn/' },
      { name: '中国银河金融控股有限责任公司', url: 'http://www.china-galaxy.com.cn/' },
    ],
  },
  {
    category: '中央文化企业',
    sites: [
      { name: '中国方正出版社有限公司', url: 'http://www.lianzheng.com.cn/' },
      { name: '党建读物出版社有限公司', url: 'http://djcb.12371.cn/' },
      { name: '中国出版集团有限公司', url: 'http://www.cnpubg.com/' },
      { name: '中国新闻出版传媒集团有限公司', url: 'http://www.chinaxwcb.com/node/171' },
      { name: '五洲传播出版传媒有限公司', url: 'http://m.cicc.org.cn/' },
      { name: '学习出版社有限公司', url: 'http://www.xuexiph.cn/' },
      { name: '线装书局有限公司', url: 'http://www.zgxzsj.com/#/' },
      { name: '中国书籍出版社有限公司', url: 'http://www.chinabp.com.cn/' },
      { name: '宗教文化出版社有限公司', url: 'http://www.zjwhcbs.com/zj/index.html' },
      { name: '当代世界出版社有限公司', url: 'http://www.ddsjcn.com/' },
      { name: '世界知识出版社有限公司', url: 'http://www.ishizhi.cn/web/c_000000040045/' },
      { name: '中国计划出版社有限公司', url: 'http://www.jhpress.com/' },
      { name: '中国市场出版社有限公司', url: 'http://www.scpress.cn/#/' },
      { name: '中国教育出版传媒集团有限公司', url: 'http://www.cepmg.com.cn/' },
      { name: '教育科学出版社有限公司', url: 'http://www.esph.com.cn/default.aspx' },
      { name: '科学技术文献出版社有限公司', url: 'http://www.stdp.com.cn/' },
      { name: '中国工信出版传媒集团有限责任公司', url: 'http://www.ciitp.com.cn/' },
      { name: '中国民族文化出版社有限公司', url: 'http://www.cncpress.cn/' },
      { name: '中国社会出版社有限公司', url: 'https://shcbs.mca.gov.cn/' },
      { name: '法律出版社有限公司', url: 'http://www.lawpress.com.cn/' },
      { name: '中国法制出版社有限公司', url: 'http://qianwen/www.zgfzs.com/' },
      { name: '中国财经出版传媒集团有限责任公司', url: 'http://qianwen/www.cfemg.cn' },
      { name: '中国人力资源和社会保障出版集团有限公司', url: 'http://www.class.com.cn/' },
      { name: '中国地图出版社有限公司', url: 'http://www.sinomaps.com/' },
      { name: '海洋出版社有限公司', url: 'http://www.oceanpress.com.cn/' },
      { name: '地质出版社有限公司', url: 'http://www.gph.com.cn/#/geologicalSociety' },
      { name: '中国大地出版社有限公司', url: 'http://www.chinalandpress.com/#/dadiSociet' },
      { name: '成都地图出版社有限公司', url: 'http://www.ccph-map.com/' },
      { name: '哈尔滨地图出版社有限公司', url: 'http://www.hcph.com.cn/' },
      { name: '中国环境出版集团有限公司', url: 'http://www.cesp.com.cn/' },
      { name: '中国环境报社有限公司', url: 'http://www.cenews.com.cn/' },
      { name: '中国建筑出版传媒有限公司', url: 'http://www.cabp.com.cn/index' },
      { name: '中国城市出版社有限公司', url: 'http://zgcscbs.show.imosi.com/' },
      { name: '人民交通出版传媒管理有限公司', url: 'http://www.ccpress.com.cn/' },
      { name: '中国交通报社有限公司', url: 'http://www.zgjtb.com/' },
      { name: '中国水运报社有限公司', url: 'http://www.zgsyb.com/' },
      { name: '中国水利水电出版传媒集团有限公司', url: 'http://www.waterpub.com.cn/' },
      { name: '中国农业出版社有限公司', url: 'http://www.ccap.com.cn/' },
      { name: '中国农业科学技术出版社有限公司', url: 'http://www.castp.cn/' },
      { name: '中国商务出版社有限公司', url: 'http://www.cctpress.com/#/index' },
      { name: '中国文化传媒集团有限公司', url: 'http://www.ccmg.cn/' },
      { name: '中国东方演艺集团有限公司', url: 'http://www.dfyanyi.com/index.html' },
      { name: '国家图书馆出版社有限公司', url: 'http://www.nlcpress.com/' },
      { name: '中国动漫集团有限公司', url: 'http://www.acgnet.cn/' },
      { name: '中国数字文化集团有限公司', url: 'http://www.cdcgc.com.cn/' },
      { name: '故宫出版社有限公司', url: 'http://www.dpm.org.cn/publishes.html' },
      { name: '文化艺术出版社有限公司', url: 'http://www.caaph.com/' },
      { name: '中国旅游出版社有限公司', url: 'http://www.cttp.net.cn/' },
      { name: '人民卫生出版社有限公司', url: 'http://www.pmph.com/' },
      { name: '健康报社有限公司', url: 'http://www.jkb.com.cn/aboutus/' },
    ],
  },
  {
    category: '央企&名企招聘',
    sites: [
      { name: '招商局集团有限公司', url: 'https://www.cmhk.com/main/rlzy/index.shtml' },
      { name: '中国建设银行', url: 'https://job3.ccb.com/cn/job/index.html' },
      { name: '华润（集团）有限公司', url: 'https://www.crc.com.hk/talent/concepts/' },
      { name: '中国银行', url: 'https://www.boc.cn/aboutboc/bi4/' },
      { name: '应急管理出版社有限公司', url: 'http://www.cciph.com.cn/' },
      { name: '中国旅游集团有限公司[香港中旅（集团）有限公司]', url: 'https://www.ctg.cn/talent-concept' },
      { name: '招商银行', url: 'https://career.cmbchina.com/home' },
      { name: '中国金融出版社有限公司', url: 'http://www.cnfinance.cn/' },
      { name: '中国商用飞机有限责任公司', url: 'https://zhaopin.comac.cc/' },
      { name: '兴业银行', url: 'https://www.cib.com.cn/cn/aboutCIB/about/jobs/2022/index.html_917596316.html' },
      { name: '中国时代经济出版社有限公司', url: 'http://zgsdjjcbs.chineseall.cn/' },
      { name: '中国节能环保集团有限公司', url: 'https://www.cecep.cn/cecep/zyly/rczp/jngs/A008014003001Gone1.html' },
      { name: '中信银行', url: 'https://job.citicbank.com/' },
      { name: '化学工业出版社有限公司', url: 'http://www.cip.com.cn/' },
      { name: '中国国际工程咨询有限公司', url: 'http://www.ciecc.com.cn/col/col1627/index.html' },
      { name: '中国光大银行', url: 'https://cebbank.51job.com/index.html' },
      { name: '中国轻工业出版社有限公司', url: 'http://chlip.com.cn/' },
      { name: '中国诚通控股集团有限公司', url: 'http://www.cctgroup.com.cn/cctgroup/rlzy/rczp/index.html' },
      { name: '华夏银行', url: 'http://hxb.com.cn/jrhx/cpyc/index.shtml#' },
      { name: '中国纺织出版社有限公司', url: 'http://www.c-textilep.com/main/' },
      { name: '中国中煤能源集团有限公司', url: 'https://www.chinacoal.com/col/col225/index.html' },
      { name: '广发银行', url: 'https://www.cgbchina.com.cn/Channel/11581868' },
      { name: '冶金工业出版社有限公司', url: 'http://www.mip1953.com/' },
      { name: '中国煤炭科工集团有限公司', url: 'https://www.ccteg.cn/zh/article/textList/70#menuDom' },
      { name: '江苏银行', url: 'https://hr.jsbchina.cn/spa/custom/static/index.html#/main/cs/app/415469a50449415a9b56642c69728966_jscb?_key=bws1ga' },
      { name: '中国机械科学研究总院集团有限公司', url: 'https://www.cam.com.cn/channels/175.html' },
      { name: '浙商银行', url: 'https://zp.czbank.com.cn/zpweb/zpweb.do' },
      { name: '中国商业出版社有限公司', url: 'http://www.zgsycb.com/#/' },
      { name: '中国钢研科技集团有限公司', url: 'http://www.cisri.com.cn/rlzy/rczm.htm' },
      { name: '重庆农村商业银行', url: 'https://campus.51job.com/CQRCB2023/index.html' },
      { name: '企业管理出版社有限公司', url: 'http://www.emph.cn/' },
      { name: '中国化学工程集团有限公司', url: 'https://www.cncec.cn/articlepagelist/zpxx' },
      { name: '徽商银行', url: 'http://rczp.hsbank.com.cn:8000/job/Channel/5938' },
      { name: '中国海关出版社有限公司', url: 'http://www.hgcbs.com.cn/' },
      { name: '中国盐业集团有限公司', url: 'http://www.chinasalt.com.cn/rlzy/rczp/' },
      { name: '杭州银行', url: 'https://myjob.hzbank.com.cn/hzzp-apply/dist/static/index.html#/index' },
      { name: '中国税务出版社有限公司', url: 'https://www.taxation.cn/' },
      { name: '中国建材集团有限公司', url: 'http://www.cnbm.com.cn/CNBM/000000090005/index.html' },
      { name: '盛京银行', url: 'https://zhaopin.shengjingbank.com.cn:8080/zp.html' },
      { name: '中国质量标准出版传媒有限公司', url: 'http://www.spc.net.cn/' },
      { name: '中国有色矿业集团有限公司', url: 'https://hrcnmc.iguopin.com/' },
      { name: '中原银行', url: 'https://zybank.zhiye.com/' },
      { name: '中国工商出版社有限公司', url: 'http://www.cicpress.com/' },
      { name: '中国稀土集团有限公司', url: 'https://www.regcc.cn/zgxtjt/zpdt/list.shtml' },
      { name: '厦门国际银行', url: 'https://xib.zhiye.com/' },
      { name: '中国广播电视网络集团有限公司', url: 'http://www.cbn.cn/' },
      { name: '中国有研科技集团有限公司', url: 'https://www.grinm.com/2603.html' },
      { name: '汇丰银行', url: 'https://mycareer.hsbc.com/en_GB/external' },
      { name: '中广传播集团有限公司', url: 'http://cbc.cn.statscrop.com/' },
      { name: '矿冶科技集团有限公司', url: 'http://www.bgrimm.com/rlzy/rczp/index.htm' },
      { name: '长沙银行', url: 'https://wecruit.hotjob.cn/SU628ddf200dcad4099b64f468/pb/index.html#/' },
      { name: '中国广播影视出版社有限公司', url: 'http://www.crtp.com.cn/' },
      { name: '中国国际技术智力合作集团有限公司', url: 'http://www.ciic.com.cn/ciic/rczp/index.html' },
      { name: '东莞农村商业银行', url: 'https://www.drcbank.com/rcr_portal/index.html#/campus-recruitment' },
      { name: '中国体育报业总社有限公司', url: 'http://www.sportsol.com.cn/Login.aspx' },
      { name: '中国建筑科学研究院有限公司', url: 'http://www.cabr.com.cn/1345.html' },
      { name: '深圳农商银行', url: 'https://wecruit.hotjob.cn/SU601ce262bef57c66a91d41fa/pb/index.html#/' },
      { name: '中国统计出版社有限公司', url: 'http://www.zgtjcbs.com/indexnew.jsp' },
      { name: '中国中车集团有限公司', url: 'https://www.crrcgc.cc/crrcgc/71_4837/71_4859/index.html' },
      { name: '广州银行', url: 'https://wecruit.hotjob.cn/SU65323a7d8ac1ca5869a66c80/pb/social.html' },
      { name: '中国言实出版社有限公司', url: 'http://www.zgyscbs.cn/' },
      { name: '中国铁路通信信号集团有限公司', url: 'http://www.crsc.cn/1095.html' },
      { name: '吉林银行', url: 'https://www.jlbank.com.cn/jlbank/gyjx/rczp/xyzp/index.html' },
      { name: '中国铁路工程集团有限公司', url: 'http://www.crecg.com/web/10089507/10091669/index.html' },
      { name: '贵州银行', url: 'https://www.bgzchina.com/article/category/c27' },
      { name: '中国电力传媒集团有限公司', url: 'http://www.cpmg.com.cn/' },
      { name: '中国铁道建筑集团有限公司', url: 'https://www.crcc.cn/col/col214/index.html' },
      { name: '江西银行', url: 'https://www.jx-bank.com/col226/list.html' },
      { name: '中国林业出版社有限公司', url: 'https://www.forestry.gov.cn/c/www/rszkzp.jhtml' },
      { name: '中国交通建设集团有限公司', url: 'https://www.ccccltd.cn/rlzy/rczp/zpgg/zpgg_zgjjzp/' },
      { name: '苏州银行', url: 'https://hr.suzhoubank.com/zpweb.do' },
      { name: '中国民航报社', url: 'http://www.caacnews.com.cn/' },
      { name: '中国信息通信科技集团有限公司', url: 'https://campus.51job.com/cict2024/about.html' },
      { name: '江苏江南农村商业银行', url: 'http://hr.jnbank.com.cn/?v=1712560901532' },
      { name: '中国民航出版社有限公司', url: 'http://www.ccaph.com/' },
      { name: '中国农业发展集团有限公司', url: 'https://www.cnadc.com.cn/tzgg/index.jhtml' },
      { name: '顺德农商银行', url: 'https://www.sdebank.com/mainsite/rczp/index.html' },
      { name: '文物出版社有限公司', url: 'http://www.wenwu.com/sy' },
      { name: '中国林业集团有限公司', url: 'http://www.cfgc.cn/g4453.aspx' },
      { name: '四川银行', url: 'https://www.scbank.cn/cn/col307/index.html' },
      { name: '中国文物报社有限公司', url: 'http://www.sjycxy.com/' },
      { name: '中国医药集团有限公司', url: 'http://www.sinopharm.com/recruitment.html' },
      { name: '东莞银行', url: 'https://dongguanbank.zhiye.com/' },
      { name: '中国中医药出版社有限公司', url: 'http://www.cptcm.com/' },
      { name: '中国保利集团有限公司', url: 'https://mp.weixin.qq.com/s/nu5IzsUUnAjqGeysh4mHtg' },
      { name: '河北银行', url: 'https://hebbank.zhiye.com/home' },
      { name: '中国中医药报社有限公司', url: 'http://www.cntcm.com.cn/' },
      { name: '中国建设科技有限公司', url: 'https://www.cctc.cn/rczp/rlzy/xyzp/index.shtml' },
      { name: '青岛银行', url: 'https://hr.qdboffice.com/recruit/talent/official.html#/main' },
      { name: '中医古籍出版社有限公司', url: 'http://www.zygjcbs.cn/' },
      { name: '中国冶金地质总局', url: 'https://www.cmgb.com.cn/cmgb/84783/85056/index.html' },
      { name: '西安银行', url: 'https://job.xacbank.com:8001/' },
      { name: '中国健康传媒集团有限公司', url: 'http://www.cmstpx.com/' },
      { name: '中国煤炭地质总局', url: 'http://www.ccgc.cn/?mod=zhaopin&tid=129' },
      { name: '珠海华润银行', url: 'https://crc.wintalent.cn/wt/crcbank/web/index?brandCode=1' },
      { name: '知识产权出版社有限责任公司', url: 'http://www.ipph.cn/' },
      { name: '新兴际华集团有限公司', url: 'http://www.xxcig.com/web/xwzx/jtgg/index.shtml' },
      { name: '渣打银行', url: 'https://www.sc.com/en/global-careers/early-careers/apply/' },
      { name: '金城出版社有限公司', url: 'http://www.jccb.com.cn/' },
      { name: '中国民航信息集团有限公司', url: 'http://www.travelsky.cn/publish/main/38/61/258/index.html' },
      { name: '九江银行', url: 'https://hotjob.cn/wt/JJYH/web/index?aisiteOutPageId=fc4d24204dc841b0a86957d2fbfa9516' },
      { name: '中国航空油料集团有限公司', url: 'http://www.cnaf.com/PORTAL_LNG_RLS_XWGJ.getFormList.do?LM_CODE=CNAF_HR_RCZLHLN&LM_CONTENT_TYPE=2' },
      { name: '兰州银行', url: 'https://www.lzbank.com/public/pjiarulh/' },
      { name: '中国航空器材集团有限公司', url: 'http://www.casc.com.cn/cas/?cat=16' },
      { name: '台州银行', url: 'https://www.hotjob.cn/wt/TZBANK/web/index?brandCode=1' },
      { name: '中国检察出版社有限公司', url: 'http://www.zgjccbs.com/' },
      { name: '中国电力建设集团有限公司', url: 'https://zhaopin.powerchina.cn/index' },
      { name: '浙江泰隆商业银行', url: 'https://zjtlcb.zhiye.com/' },
      { name: '中国少年儿童新闻出版总社有限公司', url: 'http://www.ccppg.cn/' },
      { name: '中国能源建设集团有限公司', url: 'https://www.ceec.net.cn/col/col11057/index.html' },
      { name: '晋商银行', url: 'https://www.jshbank.com/jsyh/index/jssy/gsgg/index.html' },
      { name: '中国青年出版总社有限公司', url: 'http://www.cyp.com.cn/' },
      { name: '中国安能建设集团有限公司', url: 'https://www.china-an.cn/index.php/talentRecruitment.html' },
      { name: '浙江稠州商业银行', url: 'https://czcb.zhiye.com/' },
      { name: '中国妇女出版社有限公司', url: 'http://www.womenbooks.cn/' },
      { name: '中国黄金集团有限公司', url: 'http://www.chinagoldgroup.com/2386.html' },
      { name: '广西北部湾银行', url: 'https://www.bankofbbg.com/bbgow/gywx/xwzx/rczp/index.html' },
      { name: '中国广核集团有限公司', url: 'http://www.cgnpc.com.cn/cgn/c101066/zhaopin.shtml' },
      { name: '富滇银行', url: 'https://www.fudian-bank.com/index.html' },
      { name: '中国文联出版社有限公司', url: 'http://www.clapnet.cn/' },
      { name: '华侨城集团有限公司', url: 'https://oct.zhaopin.com/' },
      { name: '三井住友银行', url: 'https://www.smbc.co.jp/global/careers/' },
      { name: '中国摄影出版传媒有限公司', url: 'http://www.cpph.com/' },
      { name: '南光（集团）有限公司[中国南光集团有限公司]', url: 'https://wecruit.hotjob.cn/SU655d95021eb805776cb6f5d9/pb/index.html#/' },
      { name: '东亚银行', url: 'https://www.hkbea.com/html/en/bea-career-landing.html?' },
      { name: '中国书法出版传媒有限责任公司', url: 'http://www.zgsfcbcm.com/' },
      { name: '中国电气装备集团有限公司', url: 'https://cee-campus.zhaopin.com/' },
      { name: '山西银行', url: 'https://www.shxibank.com/sxyh/jrsc/gszp/index.shtml' },
      { name: '中国物流集团有限公司', url: 'https://chinalogisticsgroup.hotjob.cn/SU643df049bef57c46afe5ed7c/mc/index' },
      { name: '威海市商业银行', url: 'https://www.whccb.com/publish/whccb/1469/index.html' },
      { name: '作家出版社有限公司', url: 'http://www.zuojiachubanshe.com/portal/gywm/zpxx/webinfo/2014/07/1564032748666837.htm' },
      { name: '中国国新控股有限责任公司', url: 'https://zp.crhc.cn/recportal/recruit_02?title=recruit_02&recruitType=02&recordId=30646438-3733-3334-2D31-3937632D3131&isCanDelete=2' },
      { name: '唐山银行', url: 'https://www.ts-bank.cn/tsbank/ppgs/cpyc/index.html' },
      { name: '中国科学技术出版社有限公司', url: 'http://www.cspbooks.com.cn/index.php' },
      { name: '中国检验认证（集团）有限公司', url: 'https://wecruit.hotjob.cn/SU637b4abd0dcad415782e833a/pb/school.html' },
      { name: '张家口银行', url: 'https://www.zjkccb.com/zjkbank/gyjy/rczp/index.html' },
      { name: '中国华侨出版社有限公司', url: 'http://0900.cn.globalimporter.net/' },
      { name: '广东南粤银行', url: 'https://www.gdnybank.com/jobnews/index.html#mao_c' },
      { name: '华夏出版社有限公司', url: 'http://www.hxph.com.cn/' },
      { name: '浙江网商银行', url: 'https://www.mybank.cn/' },
      { name: '中华工商联合出版社有限责任公司', url: 'http://zhgslh.etlong.com/' },
      { name: '团结出版社有限公司', url: 'http://www.tjpress.com/' },
      { name: '群言出版社有限公司', url: 'http://www.qypublish.com/' },
      { name: '开明出版社有限公司', url: 'http://www.kaimingpress.com/' },
      { name: '学苑出版社有限公司', url: 'http://www.book001.com/' },
      { name: '台海出版社有限公司', url: 'http://www.taimeng.org.cn/thcbs/' },
      { name: '中国铁道出版社有限公司', url: 'http://www.tdpress.com/' },
    ],
  },
  {
    category: '银行招聘',
    sites: [
      { name: '中国工商银行', url: 'https://job.icbc.com.cn/pc/index.html' },
      { name: '中国农业银行', url: 'https://career.abchina.com.cn/build/index.html#/' },
      { name: '交通银行', url: 'https://job.bankcomm.com/#/' },
      { name: '中国邮政储蓄银行', url: 'https://www.psbc.com/cn/gyyc/rczp/xyzp/' },
      { name: '上海浦东发展银行', url: 'https://job.spdb.com.cn/' },
      { name: '中国民生银行', url: 'https://www.cmbc.com.cn/sy/hd/2023/08/2074311719114940.htm' },
      { name: '平安银行', url: 'https://campus.pingan.com/' },
      { name: '北京银行', url: 'https://bankofbeijing.zhiye.com/custom/index' },
      { name: '上海银行', url: 'https://bosc.zhiye.com/' },
      { name: '宁波银行', url: 'https://zhaopin.nbcb.com.cn/' },
      { name: '南京银行', url: 'https://job.njcb.com.cn/#/home' },
      { name: '上海农商银行', url: 'https://heros.shrcb.com/recruit/talent/official.html#/shrcb' },
      { name: '渤海银行', url: 'http://www.cbhb.com.cn/bhbank/S101/jiaruwomen/index.htm' },
      { name: '恒丰银行', url: 'https://career.hfbank.com.cn/' },
      { name: '北京农商银行', url: 'https://www.bjrcb.com/pc/cn/aboutus/rczp/xyzp/list.shtml' },
      { name: '广州农商银行', url: 'https://grcbank.zhiye.com/?aisiteOutPageId=72fdd99e0aa44f28803e2b0145f8f7a4' },
      { name: '天津银行', url: 'https://www.bankoftianjin.com/tianjincareer/index/index.html' },
      { name: '成都银行', url: 'https://www.bocd.com.cn/rczp.html' },
      { name: '贵阳银行', url: 'https://job.bankgy.com:7000/zp.html#/' },
      { name: '成都农商银行', url: 'https://www.cdrcb.com/pin/' },
      { name: '哈尔滨银行', url: 'https://www.hrbb.com.cn/harBinBank/jrhx/hxzp/index.html#leftBox' },
      { name: '重庆银行', url: 'http://www.cqcbank.com/cn/jrch/rczp/xyzp/index.html' },
      { name: '郑州银行', url: 'https://wecruit.hotjob.cn/SU64f952b41eb8051fabaed066/pb/index.html#/' },
      { name: '昆仑银行', url: 'https://www.klb.cn/eportal/ui?pageId=488946' },
      { name: 'WeBank微众银行', url: 'https://hr.webank.com/apply/webankhr/68/#/' },
      { name: '桂林银行', url: 'https://app.mokahr.com/apply/guilinbank/37310#/' },
      { name: '天津农商银行', url: 'https://www.trcbank.com.cn/class/jobs/' },
      { name: '甘肃银行', url: 'https://www.gsbankchina.com/gsyh/gywm/rczp/xyzp/index.shtml' },
      { name: '大连银行', url: 'https://www.bankofdl.com/home/pc/gywm/cpyc/rczp/index.shtml' },
      { name: '青岛农商银行', url: 'https://www.qrcb.com.cn/qrcb/rczp/#/home' },
      { name: '齐鲁银行', url: 'https://www.qlbchina.com/qlbchina/rczp/shzp/zpgg/index.html' },
      { name: '湖南银行', url: 'https://www.hunan-bank.com/96599/gywx/rczp/index.shtml' },
      { name: '湖北银行', url: 'http://www.hubeibank.cn/cn/rczp/zhbbzp/index.html' },
      { name: '杭州联合银行', url: 'https://www.urcb.com/urcb/gyyl1/rczp/zpgg/index.shtml' },
      { name: '汉口银行', url: 'http://hr.hkbchina.com/hire/hireNetPortal/zp_homepage.do?b_hquery=link?&cms_chl_no=502&menuType=0&chl_id=502' },
      { name: '花旗银行', url: 'https://jobs.citi.com/search-jobs' },
      { name: '长安银行', url: 'https://job.ccabchina.com/' },
      { name: '武汉农村商业银行', url: 'http://www.whrcbank.com/zhuzhan/PersonnelRecruitment/?1ggKwf2G=fmGnbqlqEcBgSQDIi0vP0DTaPNQtFprtN0NOi72DJjGm7J1szV7UExgeY58c.jrUcF.jXTq8iaI.FpHeskJoeFZfsX5_qjG7' },
      { name: '南海农商银行', url: 'http://www.nanhaibank.com/zpgg/index.html' },
      { name: '三菱东京日联银行', url: 'https://www.bk.mufg.jp/global/careers/index.html' },
      { name: '常熟农商银行', url: 'http://www.csrcbank.com/tb/rczp/zxzp_358/' },
      { name: '温州银行', url: 'https://hr.wzbank.cn/apply/index.action' },
      { name: '广东华兴银行', url: 'https://www.ghbank.com.cn/recruit-web/home/index' },
      { name: '厦门银行', url: 'http://www.xmbankonline.com/shzp/index.html' },
      { name: '蒙商银行', url: 'http://www.gip.bsb.com.cn/homepage/rczp/' },
      { name: '廊坊银行', url: 'https://webapp.zhaopin.com/2024/hd/lfyhg0326ZL82493/' },
      { name: '瑞穗银行', url: 'https://www.mizuhogroup.com/careers' },
      { name: '萧山农商银行', url: 'https://www.zjxsbank.com/mstsc/RCZP/hr.aspx?k1=10' },
      { name: '日照银行', url: 'https://job.bankofrizhao.com.cn/' },
      { name: '重庆三峡银行', url: 'https://zhaopin.ccqtgb.com:8443/recruit#/index' },
      { name: '广西农商联合银行', url: 'https://www.gx966888.com/zpsy.jhtml' },
    ],
  },
  {
    category: '选调生&事业单位',
    sites: [
      { name: '国家公务员局（已停止更新）', url: 'http://www.scs.gov.cn/' },
      { name: '北京市各级机关2024年度考试录用公务员', url: 'https://rsj.beijing.gov.cn/bm/ztzl/gwy/' },
      { name: '天津市人事考试网上报名公共服务平台', url: 'http://rsks.hrss.tj.gov.cn/ks/index.do?method=select' },
      { name: '河北省人事考试网', url: 'https://www.hebpta.com.cn/' },
      { name: '山西人事考试', url: 'http://rst.shanxi.gov.cn/rsks/' },
      { name: '内蒙古人事考试', url: 'http://www.impta.com.cn/' },
      { name: '辽宁人事考试网', url: 'https://www.lnrsks.com/' },
      { name: '黑龙江省选调生工作网', url: 'https://gongxuan.ljxfw.gov.cn/' },
      { name: '上海市公务员考试报名系统', url: 'http://bm.shacs.gov.cn/zlxt/zlxt/index/' },
      { name: '江苏公务员考录专题', url: 'http://www.jszzb.gov.cn/col95/list.html' },
      { name: '安徽先锋网人事考试', url: 'https://www.ahxf.gov.cn/Home/List/6622' },
      { name: '福建省公务员考试录用网', url: 'https://gwykl.fujian.gov.cn/Portal/klnews' },
      { name: '湖北省人事考试网', url: 'http://www.hbsrsksy.cn/' },
      { name: '湖南人事考试网', url: 'http://www.hunanpea.com/' },
      { name: '七一网（选调生招录）', url: 'https://www.12371.gov.cn/Category_1514/Index_2.aspx' },
      { name: '四川省人力资源和社会保障厅（人事考试）', url: 'https://www.scpta.com.cn/index.aspx' },
      { name: '灯塔-党建在线（录用选调生）', url: 'https://www.dtdjzx.gov.cn/staticPage/sdsxdyxgxbysdcrzw/xdtzgg/xdtzgg.html' },
      { name: '山东人事考试网', url: 'http://hrss.shandong.gov.cn/rsks/' },
      { name: '河南省选调生网', url: 'http://xds.haedu.gov.cn/' },
      { name: '甘肃公务员', url: 'http://www.gszg.gov.cn/' },
      { name: '甘肃选调生', url: 'http://www.gszg.gov.cn/2024xds/index.htm' },
      { name: '广东组织工作', url: 'https://www.gdzz.gov.cn/gwygz/lypytzgg/index.html' },
      { name: '广东人事考试网', url: 'https://rsks.gd.gov.cn/wsbs/gwyks/2023/index.html' },
      { name: '八桂先锋公务员招考录用', url: 'https://www.bgxf.gov.cn/staticmores/392/392-1.shtml' },
      { name: '广西人事考试网', url: 'http://www.gxpta.com.cn/' },
      { name: '贵州党建云 选调', url: 'https://www.gzzzb.gov.cn/tzgg/20230106/20230106_086624.shtml' },
      { name: '贵州人事考试信息网', url: 'http://www.gzrsks.com.cn/' },
      { name: '青海党建', url: 'http://api.qhsdj.gov.cn/html/gsgg/' },
      { name: '青海省人事考试信息网选调公务员', url: 'http://weixin.qhpta.com/ncms/index_m.shtml' },
      { name: '宁夏党建', url: 'http://www.nxdjw.gov.cn/nxdjgsgg/' },
      { name: '宁夏人事考试中心网', url: 'https://www.nxpta.com/gwyks/index_1.html' },
    ],
  },
  {
    category: '地方人社&事业编',
    sites: [
      { name: '河北', url: 'https://rst.hebei.gov.cn/a/kaoshizhaopin/' },
      { name: '山西', url: 'http://rst.shanxi.gov.cn/ztzl/zpxx/' },
      { name: '内蒙古', url: 'https://rst.nmg.gov.cn/xwzx/gsgg/202307/t20230705_2342547.html' },
      { name: '辽宁', url: 'http://www.lnrsks.com/' },
      { name: '黑龙江', url: 'http://hrss.hlj.gov.cn/hrss/index.shtml' },
      { name: '江苏', url: 'https://jshrss.jiangsu.gov.cn/col/col57437/index.html' },
      { name: '安徽', url: 'http://hrss.ah.gov.cn/zxzx/ztzl/ahsszsydwgkzpzl/index.html' },
      { name: '福建', url: 'https://rst.fujian.gov.cn/zw/ztzl/zxzt/sydwrczp/' },
      { name: '湖北', url: 'https://rst.hubei.gov.cn/bmdt/ztzl/ywzl/hbsszsydwgkzp/' },
      { name: '湖南', url: 'http://rst.hunan.gov.cn/rst/xxgk/zpzl/sydwzp/index.html' },
      { name: '四川', url: 'https://www.scpta.com.cn/' },
      { name: '山东', url: 'http://hrss.shandong.gov.cn/channels/ch00232/' },
      { name: '河南', url: 'https://ywzl.hrss.henan.gov.cn/viewCmsCac.do?cacId=4aef1408279926e601279e53eac517a5' },
      { name: '甘肃', url: 'https://rst.gansu.gov.cn/rst/c113804/202307/169880613.shtml' },
      { name: '广东', url: 'https://hrss.gd.gov.cn/zwgk/sydwzp/' },
      { name: '广西', url: 'http://rst.gxzf.gov.cn/ztjj/ztjjrdzt/cfxd/' },
      { name: '贵州', url: 'http://rst.guizhou.gov.cn/zwgk/zdlyxx/sydwgkzp/' },
      { name: '青海', url: 'http://www.qhpta.com/ncms/sydwks.shtml' },
      { name: '宁夏', url: 'https://www.nxpta.com/sydwzk/index.html' },
      { name: '吉林', url: 'http://hrss.jl.gov.cn/rsrc/sydwrsgl/gkzp/' },
      { name: '浙江', url: 'http://rlsbt.zj.gov.cn/col/col1443681/index.html' },
      { name: '江西', url: 'http://rst.jiangxi.gov.cn/col/col47831/index.html' },
      { name: '云南', url: 'http://hrss.yn.gov.cn/NewsLsit.aspx?ClassID=602' },
      { name: '陕西', url: 'http://www.shaanxi.gov.cn/xw/ztzl/zxzt/zkzl/' },
      { name: '海南', url: 'http://hrss.hainan.gov.cn/hrss/sydwzp/list3.shtml' },
      { name: '西藏', url: 'https://hrss.xizang.gov.cn/zpxx/' },
      { name: '新疆', url: 'https://rst.xinjiang.gov.cn/xjrst/c112746/list.shtml' },
    ],
  },
  {
    category: '求职工具&资源',
    sites: [
      { name: 'Campus2026', url: 'https://github.com/namewyf/Campus2026', desc: '2026届校招信息汇总，社区共创维护' },
      { name: 'CampusShame', url: 'https://github.com/forthespada/CampusShame', desc: '校招污点行为记录，帮你避雷毁约鸽offer的企业' },
      { name: '牛客网', url: 'https://www.nowcoder.com/', desc: '校招笔试面试刷题平台，含校招日历、面经' },
      { name: '牛客面经', url: 'https://www.nowcoder.com/discuss' },
      { name: '实习僧', url: 'https://www.shixiseng.com/', desc: '国内领先的实习招聘平台' },
      { name: 'LeetCode(刷题)', url: 'https://leetcode.cn/' },
      { name: '超级简历', url: 'https://www.wondercv.com/' },
      { name: '知页简历', url: 'https://www.zhiyeapp.com/' },
      { name: '看准网(薪资)', url: 'https://www.kanzhun.com/' },
      { name: '职友集(薪资)', url: 'https://www.jobui.com/' },
      { name: 'OfferShow', url: 'https://offershow.cn/' },
      { name: '脉脉(职场社交)', url: 'https://maimai.cn/' },
      { name: '领英LinkedIn', url: 'https://www.linkedin.com/' },
    ],
  },
];

/** 把完整 URL 格式化为简洁的域名提示 */
export function formatNavUrl(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, '');
  } catch {
    return url;
  }
}
